### ISSUE TITLE
Authorization failed on fission register

### ISSUE THREAD

**Issue by bmann** [fission-suite/cli#20]
I tried registering, got Authorization Failed, and realized I had an old version of the CLI. Got the new version, same Authorization Failed error.

<img width="251" alt="Screenshot 2019-11-03 21 51 30" src="https://user-images.githubusercontent.com/280420/68101853-a17d6a80-fe84-11e9-9780-3258004224ac.png">

**Comment by expede** [comment]
@bmann have you tried to register with the name `boris` before? Usernames need to be unique. We need to return a clearer message here regardless.

**Comment by bmann** [comment]
Sorry forgot to come back and close this. Once you did your fixes on the server this was resolved.
