### ISSUE TITLE
Segmentation fault in `fission watch` after update

### ISSUE THREAD

**Issue by AronVanAmmers** [fission-suite/cli#21]
# Summary

## Problem

I'm getting this consistently with `fission watch` on a directory with a single small file `index.html`:

```
$ fission watch
👀 Watching ./ for changes...
🚀 Now live on the network
👌 QmYeCjNt5SSW7xW9kuM6QyEgAGDNQ1pfsAZNbroVcRh5k1
📝 DNS Updated. Check out your site at:
🔗 aron.fission.name
🕐Segmentation fault (core dumped)
```

The update works correctly, but `fission watch` crashes.

### Impact

`fission watch` completes only one update and crashes.

## Solution

Fix the segmentation fault

# Detail

**Describe the bug**

**To Reproduce**
1. `cd fission-test` (the directory to go live from laptop)
2. Run `fission watch`
3. In other terminal window, edit `index.html` in the `fission-test` directory
4. Review terminal with `fission watch` in it
4. See error:

```
$ fission watch
👀 Watching ./ for changes...
🚀 Now live on the network
👌 QmYeCjNt5SSW7xW9kuM6QyEgAGDNQ1pfsAZNbroVcRh5k1
📝 DNS Updated. Check out your site at:
🔗 aron.fission.name
🕐Segmentation fault (core dumped)
```

**Expected behavior**
`fission watch` would stay open, and when I made another change, would update the online version again.

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04
- Browser: none, just using `fission` through the CLI
- Fission version: 1.15.1
- go-ipfs version: 0.4.22

**Comment by bmann** [comment]
@AronVanAmmers we've tracked this down to the way we build Linux binaries. Static builds are big. Dynamic builds are small, but require dependencies. There is a new release, but that probably won't work for you right now.

We're automating this process and need to build apt packages as the best solution long term for linux users.

(also moved this to the CLI repo)

**Comment by AronVanAmmers** [comment]
👌 yay apt packages 😄. As a quick workaround, if you know the common dependencies needed, adding a `sudo apt install` oneliner in the setup instructions could cover it.

**Comment by dholms** [comment]
@AronVanAmmers it's actually only one dependency that you need. We've updated the [install instructions](https://app.gitbook.com/@runfission/s/fission-guide/installation#linux-and-manual-macos) and cut a [new release](https://github.com/fission-suite/cli/releases/tag/1.20.0)(bonus, with some package compression, the Linux binary is now smaller than the macOS one!). Just grab that binary and install `libpq-dev`. This works fine for me on a clean install of Ubuntu 18.04. But let us know how it goes for you!

**Comment by expede** [comment]
We're also working on removing the dependency, and creating a new static binary (that hopefully doesn't segfault when linked). We're also going to try building with different versions of gcc/libc (the internet indicates that this has some decent chance of working)

**Comment by expede** [comment]
To move some of the discussion and plan from internal channels to here

## Non-static Binary

* [ ] Confirm that the updated binary (@dholms's comment) works for @AronVanAmmers 
* [ ] Build on older gcc/libc for improved compatibility with older Linuxes

## Static Bianry Plan

* [ ] Split out IPFS components to remove pg sub-dependency
* [ ] Update `cli`
* [ ] Build static binary under various gcc/libc

**Comment by AronVanAmmers** [comment]
I've tested the new binary and installing the one dependency `libpq-dev` on the same system as before ☝️. Have not seen any segfaults anymore 🎉, even while making lots of changes in rapid succession (which would trigger the segfault before quite reliably).

Also shutting down `ipfs daemon` while `fission watch` is running doesn't lead to a segfault anymore - it stays spinning and when I fire up `ipfs daemon` again it processes all changes.

And starting `fission watch` without `ipfs daemon` running gives a similar result - no error message anymore, it reports one successful upload:

```
$ fission watch
👀 Watching ./ for changes...
🚀 Now live on the network
👌 QmcqZtfVx9fFphhjXRjBrgzbSxZXqSnBgNyNcMEQPD1Na4
📝 DNS Updated. Check out your site at:
🔗 aron.fission.name
```

Then stays spinning when further changes happen, and when starting `ipfs daemon` again, processes those changes too:

```
🚀 Now live on the network
👌 Qmd4wPNPY7ZBX4EvYF9cjaBY7bcQyA7kaaDetPkBvtzMGi
📝 DNS Updated. Check out your site at:
🔗 aron.fission.name
🚀 Now live on the network
👌 QmdSdn7DRLBvyvovttKs1UvAZjDbzmy4Z2NH2LzCwCLKeH
📝 DNS Updated. Check out your site at:
🔗 aron.fission.name
```

All in all a lot more robust 💪

**Comment by bmann** [comment]
I'm going to close this, we may ask you to test with the new automated binaries. Still need to make apt packages for best experiences. But IPFS isn't packaged, which is SUPER annoying.
