### ISSUE TITLE
Fission up: `Something went wrong` error

### ISSUE THREAD

**Issue by theoturner** [fission-suite/cli#22]
Ubuntu 18.04.

1. Installed according to [the guide](https://guide.fission.codes/installation).
2. Created the basic hello-universe page as in [the next page of the guide](https://guide.fission.codes/getting-started) and attempted to `fission up`.

Error:
```
Something went wrong. Please try again or file a bug report with Fission support at https://github.com/fission-suite/web-api/issues/new
```

N.B filing in this repo as I installed this repo's CLI.

**Comment by theoturner** [comment]
N.B. also tested the Ewok release in the previous repo - same issue.

**Comment by expede** [comment]
@theoturner thanks for the report! We're getting intermittent failures off the IPFS node. We're working to correct the issue.

Does it work if you retry the command?

[Note to self: if true above, change title to "Request to web-api timeout intermittently"]

**Comment by theoturner** [comment]
Retried a few times, same output.

**Comment by expede** [comment]
Hmm 🤔 Can you run it in verbose mode?

```bash
RIO_VERBOSE=true fission up
```

Also just to double check: do you have IPFS running?

**Comment by theoturner** [comment]
And there was the issue: WSL was shutting down my ipfs node as soon as it was up. For others with the same issue, just run a VM over WSL. No issues with Fission :)

**Comment by bmann** [comment]
Thanks @theoturner — we really want to make sure that at least stuff works on WSL. Running IPFS Desktop graphically might work better. We need to do more Windows testing. Cheers!
