### ISSUE TITLE
Add .fissionignore

### ISSUE THREAD

**Issue by dholms** [fission-suite/cli#31]
# Summary
## Problem
`up` and `watch` upload the entire directory

## Impact
Files that you don't want shared (for instance, `.env` or `.Ds_Store` can end up being uploaded to IPFS.

## Solution
Add a `.fissionignore` option similar to `.gitignore`
A few points:
- we already have a per-repo `.fission.yaml`. we can just include a `fission_ignore` section there
  - with this we should make env files per-key: create a repo's env by scanning the root dir and overwriting keys as you work your way up to the repo dir
- sensible (but overwritable) defaults: ie auto-ignore `.env` and `.Ds_Store`. Any others?

**Comment by dholms** [comment]
This feature has been in discussion in the `go-ipfs` issue boards for ~4yrs. Kept getting blocked, and now just seems to be low priority. 
Check status here:
https://github.com/ipfs/go-ipfs/issues/3643
One PR that addressed the issue but never got merged:
https://github.com/ipfs/go-ipfs/pull/4013

**Comment by bmann** [comment]
So either we:

**Run our own ignore.** This means we can’t use a local IPFS add command on a directory. We recursively do IPFS add on individual files, and then construct an IPFS DAG for the whole directory. 

**Push to get this included upstream.** I can add some comments supporting this. 

For now, I guess we de-prioritize this. Should we label as “blocked” or “upstream issue”, or?

**Comment by expede** [comment]
Yeah, we knew about this ahead of time. Sorry, this is why we should write things down, (we did discuss it on the call).

> Run our own ignore

I was thinking that this is what we do. It's nontrivial, but not a tremendous amount of work. Walk the tree recursively, building up an IPLD structure — checking if the filepaths match things in the gitignore, of course.

We can also explore using MFS for this. Steven has used that much more than me, and can advise better on advantages/disadvantages.

> Push to get this included upstream.

That would be _ideal._ @bmann can we reach out and see how likely it is that this would get merged in the next few weeks.

I won't want the go-ipfs team blocking us. We have a (somewhat manual) workaround, and needing to ignore files is already causing pain for Steven. We know that it's a useful feature, but will take a bit of effort. Where that ranks in priority order is another question, though I'm pretty sure that this isn't week of work.

**Comment by bmann** [comment]
I tweeted about this to start the ball rolling. Will leave a comment. 

It will of course take some time to merge and this is a DX issue so yes, we should go ahead with our own approach. 

@expede I don’t know what you mean by using MFS that’s different?

**Comment by dholms** [comment]
Also curious about MFS as well^

If you check the issue above, someone from the IPFS team pointed me in the right direction, but said that reviews may take a while since they have some high-priority issues atm. I doubt we'd get merged in the timeframe we want
