### ISSUE TITLE
Error when installing with `brew install fission-cli`

### ISSUE THREAD

**Issue by agentofuser** [fission-suite/cli#37]
# Summary

```
==> Installing fission-cli from fission-suite/fission
Error: An exception occurred within a child process:
  RuntimeError: /usr/local/opt/ipfs not present or broken
Please reinstall ipfs. Sorry :(
```

## Problem

I have the ipfs cli installed by IPFS Desktop.

First I thought the error was because fission was looking for the ipfs cli at that absolute path (`/usr/local/opt/ipfs`), which doesn't exist.

So I symlinked it to `/Applications/IPFS\ Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs-dep/go-ipfs/ipfs`, which is what the `ipfs` command in the PATH points to.

I tried again, but I keep getting the same error.

### Impact

Show-stopper, can't install to sign up.

## Solution

Not sure how to debug this, the error message is a bit vague.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - ipfs version: 0.4.22

**Comment by bmann** [comment]
That is an interesting error. First Mac error we’ve gotten ;)

Homebrew shouldn’t depend on IPFS being installed. Will look into this.

**Comment by bechurch** [comment]
hmm I have a feeling this has to do with requiring `ipfs` in our brew formula:
https://github.com/fission-suite/homebrew-fission/blob/master/fission-cli.rb#L7

Most likely its checking that you have ipfs installed via brew.

@agentofuser would you be willing to see if install ipfs via brew solves this for you? I understand if you might have ipfs setup a certain way and we can get around to verifying this ourselves :)

**Comment by expede** [comment]
Thanks for the detailed bug report! We really appreciate these 🙏

Just to unblock, you can also download the binary here: https://github.com/fission-suite/cli/releases/download/untagged-5a7541a8d7a191642d32/macOS-10.14.zip

If IPFS is on your `PATH`, running that _should_ work 🤞

We're working on fixing the Homebrew formula to auto-detect non-brew IPFS, or at minumu  give an opt-out of the dependency.

**Comment by agentofuser** [comment]
@bechurch I installed ipfs via brew, and either before or after doing that I'm now getting the following message:

```
Error: fission-cli: Unsupported special dependency :ipfs
```

@expede thanks! I'll try the binary.

**Comment by bmann** [comment]
I heard back from @agentofuser on Discord that brew untap / tap fixed this issue. Closing!
