### ISSUE TITLE
Project-Aware CLI Sync

### ISSUE THREAD

**Issue by expede** [fission-suite/cli#4]
# Summary

The CLI currently watches & syncs the current working directory. 

## Problem

It's inconvenient to have to find your build directory, and a common mistake to invoke `up` or start `watch` from the project root. The expected behaviour is clearly to have the CLI be more project-aware.

### Impact

There's a simple workaround: `cd` into the build directory. However, autodetection is surprise-and-delight, and not having it may leave a user feeling like they've messed up.

## Solution

Detect common build directories for projects such as Jekyll, Gatsby, and so on, and sync those specifically.

**Comment by agentofuser** [comment]
This is something that I had to spend a little time doing for `ipfs-deploy`, so feel free to [copy](https://github.com/ipfs-shipyard/ipfs-deploy/blob/master/src/guess-path.js#L10).

Not all static site generators specify in their documentation what the build directory is called, so it took a bit longer than I would've liked to compile that list 😅

It's not exhaustive though, so keeping an eye on this in case you all end up covering more of the projects on staticgen.com than I had patience for.
