### ISSUE TITLE
Large files / directories fail with 500 error

### ISSUE THREAD

**Issue by bmann** [fission-suite/cli#8]
I have a directory `QmX3c6QohPeU3duLpujfc5shq8cvPhCE9WgTmubvUPVGEw` that is about 850M, filled with 2 - 3M image files. 

fission up successfully adds to IPFS locally which is how I got the hash (with debug `RIO_DEBUG=true fission up`) but then web API gives a 500 error. 

Here is the directory and hash to use with fission down for testing:

https://ipfs.runfission.com/ipfs/QmX3c6QohPeU3duLpujfc5shq8cvPhCE9WgTmubvUPVGEw

Definitely shouldn’t just 500 and in general a lot of time staring at a spinning clock emoji — more verbose output needed. 

Might be an IPFS file size / config issue?

**Comment by expede** [comment]
We've bumped up the timeout on the server to 30 minutes, so this should be okay now. We do still have issues where the CLI sometimes fails TLS and just waits for a timeout, which is filed separately (#22). Have confirmed ablility to upload large files. Our cap (via S3) should be around 5GB per pin.
